using Microsoft.CodeAnalysis;

namespace Antelcat.FlatBuffers.SourceGenerator;

[Generator]
public class FlatcLocationAttributeGenerator : IIncrementalGenerator
{
    internal const string Namespace     = "Antelcat.FlatBuffers";
    internal const string FlatcLocation = "FlatcLocation";
    internal const string FlatcArguments = "FlatcArguments";

    internal const string FlatcLocationSourceCode = $@"// <auto-generated/> Auto generated by Antelcat.FlatBuffers

namespace {Namespace}
{{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    public class {FlatcLocation} : global::System.Attribute
    {{
        /// <summary>
        /// Local disc path of flatc
        /// </summary>
        /// <param name=""path""></param>
        public {FlatcLocation}(string path){{}}
    }}
}}";
    
    internal const string FlatcArgumentsSourceCode = $@"// <auto-generated/> Auto generated by Antelcat.FlatBuffers

namespace {Namespace}
{{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    public class {FlatcArguments} : global::System.Attribute
    {{
        /// <summary>
        /// arguments used in flatc
        /// </summary>
        /// <param name=""arguments""></param>
        public {FlatcArguments}(params string[] arguments){{}}
    }}
}}";
    

    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(c =>
        {
            c.AddSource($"{Namespace}.{FlatcLocation}.cs", FlatcLocationSourceCode);
            c.AddSource($"{Namespace}.{FlatcArguments}.cs", FlatcArgumentsSourceCode);
        });
    }
}