using Microsoft.CodeAnalysis;

namespace Antelcat.FlatBuffers.SourceGenerator;

[Generator]
public class FlatcLocationAttributeGenerator : IIncrementalGenerator
{
    internal const string Namespace     = "Antelcat.FlatBuffers";
    internal const string FlatcLocation = "FlatcLocation";
    internal const string FlatcArguments = "FlatcArguments";
    internal const string FlatcReplaces = "FlatcReplaces";

    internal const string FlatcLocationSourceCode = $@"// <auto-generated/> Auto generated by Antelcat.FlatBuffers

namespace {Namespace}
{{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    internal class {FlatcLocation} : global::System.Attribute
    {{
        /// <summary>
        /// Local disc path of flatc, accepts relative path from declared file
        /// </summary>
        /// <param name=""path""></param>
        public {FlatcLocation}(string path){{}}
    }}
}}";
    
    internal const string FlatcArgumentsSourceCode = $@"// <auto-generated/> Auto generated by Antelcat.FlatBuffers

namespace {Namespace}
{{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    internal class {FlatcArguments} : global::System.Attribute
    {{
        /// <summary>
        /// arguments used in flatc
        /// </summary>
        /// <param name=""arguments""></param>
        public {FlatcArguments}(params string[] arguments){{}}
    }}
}}";
    internal const string FlatcReplacesSourceCode = $@"// <auto-generated/> Auto generated by Antelcat.FlatBuffers

namespace {Namespace}
{{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
    internal class {FlatcReplaces} : global::System.Attribute
    {{
        /// <summary>
        /// Replaces applied to all generates
        /// </summary>
        /// <param name=""from""></param>
        /// <param name=""to""></param>
        public {FlatcReplaces}(string from, string to){{}}
    }}
}}";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(c =>
        {
            c.AddSource($"{Namespace}.{FlatcLocation}.cs", FlatcLocationSourceCode);
            c.AddSource($"{Namespace}.{FlatcArguments}.cs", FlatcArgumentsSourceCode);
            c.AddSource($"{Namespace}.{FlatcReplaces}.cs", FlatcReplacesSourceCode);
        });
    }
}