using Microsoft.CodeAnalysis;

namespace Antelcat.FlatBuffers.SourceGenerator;

[Generator]
public class FlatcLocationAttributeGenerator : IIncrementalGenerator
{
    internal const string Namespace     = "Antelcat.FlatBuffers";
    internal const string AttributeName = "FlatcLocation";

    internal const string AttributeSourceCode = $@"// <auto-generated/> Auto generated by Antelcat.FlatBuffers

namespace {Namespace}
{{
    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly)]
    public class {AttributeName} : global::System.Attribute
    {{
        public {AttributeName}(string path){{}}
    }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(c =>
        {
            c.AddSource($"{Namespace}.{AttributeName}.cs", AttributeSourceCode);
        });
    }
}